/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CustomerDAO;
import Controller.EmployeeDAO;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AdminMainForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainForm
     */
    public AdminMainForm(int id) {                                  // dán dữ liệu của admin lên thôi :V 
        EmployeeDAO empDAO = new EmployeeDAO();
        initComponents();
        lbl_name.setText(empDAO.getByID(id).getFullName());
        lbl_username.setText(empDAO.getByID(id).getUsername());
        txt_phone.setText(empDAO.getByID(id).getPhoneNumber());
        txt_email.setText(empDAO.getByID(id).getEmail());
        txt_pass.setText(empDAO.getByID(id).getPassword());
        txt_address.setText(empDAO.getByID(id).getAddress());
        lbl_card.setText(empDAO.getByID(id).getIndentityCard());
    }

    private AdminMainForm() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_card = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_phone = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        but_phone = new javax.swing.JButton();
        but_email = new javax.swing.JButton();
        but_address = new javax.swing.JButton();
        but_changePassword = new javax.swing.JButton();
        but_update = new javax.swing.JButton();
        but_logout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_billActive = new javax.swing.JMenuItem();
        menu_billNegative = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_import = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_accountList = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_saleallday = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menu_member = new javax.swing.JMenuItem();

        jButton4.setText("Edit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Full name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Phone:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Indentity card:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Username:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Password:");

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_name.setText("Name");

        lbl_card.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_card.setText("card");

        lbl_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_username.setText("username");

        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_pass.setEnabled(false);

        txt_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_phone.setEnabled(false);
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });

        txt_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_address.setEnabled(false);

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_email.setEnabled(false);

        but_phone.setText("Edit");
        but_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_phoneActionPerformed(evt);
            }
        });

        but_email.setText("Edit");
        but_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_emailActionPerformed(evt);
            }
        });

        but_address.setText("Edit");
        but_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_addressActionPerformed(evt);
            }
        });

        but_changePassword.setText("Change");
        but_changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_changePasswordActionPerformed(evt);
            }
        });

        but_update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        but_update.setText("Update");
        but_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_updateActionPerformed(evt);
            }
        });

        but_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_logout.setText("Logout");
        but_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_address, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(txt_pass)
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(txt_phone)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_username)
                                    .addComponent(lbl_card)
                                    .addComponent(lbl_name))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_email, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_address, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(but_update, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_phone))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_email))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_address))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_card))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_username))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_changePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_update, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("Bill");

        menu_billActive.setText("Bill Active");
        menu_billActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_billActiveActionPerformed(evt);
            }
        });
        jMenu1.add(menu_billActive);

        menu_billNegative.setText("Bill Negative");
        menu_billNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_billNegativeActionPerformed(evt);
            }
        });
        jMenu1.add(menu_billNegative);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Import");

        menu_import.setText("Import list");
        menu_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_importActionPerformed(evt);
            }
        });
        jMenu2.add(menu_import);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Staff");

        menu_accountList.setText("Account list");
        menu_accountList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_accountListActionPerformed(evt);
            }
        });
        jMenu3.add(menu_accountList);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sale all day");

        menu_saleallday.setText("List");
        menu_saleallday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salealldayActionPerformed(evt);
            }
        });
        jMenu4.add(menu_saleallday);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Member");

        menu_member.setText("Member list");
        menu_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_memberActionPerformed(evt);
            }
        });
        jMenu5.add(menu_member);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_billActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_billActiveActionPerformed
        // Menu Bill Active
        BillActiveForm b = new BillActiveForm();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_billActiveActionPerformed

    private void menu_billNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_billNegativeActionPerformed
        // Menu Bill Negative
        BillNagativeForm bn = new BillNagativeForm();
        bn.setVisible(true);
        bn.setVisible(true);
    }//GEN-LAST:event_menu_billNegativeActionPerformed

    private void menu_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_importActionPerformed
        // Menu Import list
        ImportManager imp = new ImportManager();
        imp.setVisible(true);
        imp.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_importActionPerformed

    private void but_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_phoneActionPerformed
        // nút edit phone
        txt_phone.setEnabled(true);
    }//GEN-LAST:event_but_phoneActionPerformed

    private void but_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_emailActionPerformed
        // nút edit email
        txt_email.setEnabled(true);
    }//GEN-LAST:event_but_emailActionPerformed

    private void but_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_addressActionPerformed
        // nút edit address
        txt_address.setEnabled(true);
    }//GEN-LAST:event_but_addressActionPerformed

    private void but_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_updateActionPerformed
        // nút update thông tin 
        String user = lbl_username.getText();
        EmployeeDAO emDAO = new EmployeeDAO();
        int id = emDAO.getByUsername(user).getID();             // lấy id ra r tính :V 
        String phone = txt_phone.getText();
        String email = txt_email.getText();
        String address = txt_address.getText();
        if(phone.length()==0 || email.length()==0 || address.length()==0){
            JOptionPane.showMessageDialog(this, "You cannot delete personal information");
        }
        else{
            String regexEmail="[\\w]*[0-9]*[@][\\w]*[.][\\w]*";             // tạo 1 cái biến check email 
            String regexPhone="^(03|05|07|08|09)+[0-9]{8}$";                // tạo 1 cái biến check phone
            boolean check=false;                                            // biến check email coi true hay fasle 
            boolean check1=false;                                           // biến check phone coi true hay fasle
            Pattern pattern = Pattern.compile(regexEmail);
            Pattern pattern1 = Pattern.compile(regexPhone);
            Matcher matcher = pattern.matcher(email);
            Matcher matcher1 = pattern1.matcher(phone);
            check=matcher.find();
            check1=matcher1.find();
            if(check==false){                                          // nếu mà điền ko đúng loại email thì bắt nhập lại 
                JOptionPane.showMessageDialog(this, "Please input another email (Email by format asd123@def.com)");
            }
            else if(check1==false){                                         //  nếu mà sđt tào lao thì bắt nhập lại 
                JOptionPane.showMessageDialog(this, "Invalid phone number");
            }
            else{
                JOptionPane.showMessageDialog(this, "Successfully");             // add dc thì success :V
                emDAO.edit(phone, address, email, id);
                txt_phone.setEnabled(false);
                txt_email.setEnabled(false);
                txt_address.setEnabled(false);
            }
        }
    }//GEN-LAST:event_but_updateActionPerformed

    private void but_changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_changePasswordActionPerformed
        // nút đổi mật khẩu :V
        String user = lbl_username.getText();
        EmployeeDAO emDAO = new EmployeeDAO();
        int id = emDAO.getByUsername(user).getID();
        
        ChangePassForm change = new ChangePassForm(id);
        change.setVisible(true);
        change.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_but_changePasswordActionPerformed

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        // ràng buộc text, chỉ được nhập số
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_phoneKeyTyped

    private void menu_accountListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_accountListActionPerformed
        // Menu account list
        AccountListForm ac = new AccountListForm();
        ac.setVisible(true);
        ac.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_accountListActionPerformed

    private void but_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_logoutActionPerformed
        // nút logout 
        LoginForm l = new LoginForm();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_but_logoutActionPerformed

    private void menu_salealldayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salealldayActionPerformed
        // Menu sale all day
        SaleAllDayList s = new  SaleAllDayList();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_salealldayActionPerformed

    private void menu_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_memberActionPerformed
        // Menu member
        MemberListForm m = new MemberListForm();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_memberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_address;
    private javax.swing.JButton but_changePassword;
    private javax.swing.JButton but_email;
    private javax.swing.JButton but_logout;
    private javax.swing.JButton but_phone;
    private javax.swing.JButton but_update;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_card;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JMenuItem menu_accountList;
    private javax.swing.JMenuItem menu_billActive;
    private javax.swing.JMenuItem menu_billNegative;
    private javax.swing.JMenuItem menu_import;
    private javax.swing.JMenuItem menu_member;
    private javax.swing.JMenuItem menu_saleallday;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
