/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CustomerDAO;
import Controller.ProductDAO;
import Model.Customer;
import Model.Dish;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class ExchangeForm extends javax.swing.JFrame {

    /**
     * Creates new form ExchangeForm
     */
    public void loadData(){                                                             // Hàm tải dữ liệu bảng Product lên (lấy tất cả)
        DefaultTableModel model = (DefaultTableModel)tbl_exchange.getModel();
        ProductDAO proDAO = new ProductDAO();
        ArrayList<Product> list = proDAO.getAllDish();
        int count = model.getRowCount();
        while(count>0){
            model.removeRow(count-1);
            count--;
        }
        for(Product item:list){
            Object[] row = {item.getID(), item.getDish().getName(), item.getSize().getName(), item.getPoints()};
            model.addRow(row);
        }
    }
    
    public ExchangeForm(int idEmployee, int idCustomer, int totalAllDay, int cash, int momo, int vnpay, int discount, int idEx) {
        initComponents();
        CustomerDAO cusDAO = new CustomerDAO();
        Customer cus = cusDAO.getById(idCustomer);                              // Muốn exchange thì đầu tiên phải biết tên thằng khách trước
        lbl_user.setText(String.valueOf(idEmployee));
        lbl_cus.setText(String.valueOf(idCustomer));
        lbl_totalAllDay.setText(String.valueOf(totalAllDay));
        lbl_cash.setText(String.valueOf(cash));
        lbl_momo.setText(String.valueOf(momo));
        lbl_vnpay.setText(String.valueOf(vnpay));
        lbl_discount.setText(String.valueOf(discount));
        lbl_idEx.setText(String.valueOf(idEx));
        txt_member.setText(String.valueOf(cus.getFullName()));
        txt_points.setText(String.valueOf(cus.getPoints()));
        loadData();
    }

    private ExchangeForm() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_member = new javax.swing.JTextField();
        txt_points = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_cash = new javax.swing.JLabel();
        lbl_momo = new javax.swing.JLabel();
        lbl_vnpay = new javax.swing.JLabel();
        lbl_discount = new javax.swing.JLabel();
        lbl_idEx = new javax.swing.JLabel();
        lbl_totalAllDay = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_cus = new javax.swing.JLabel();
        but_enter = new javax.swing.JButton();
        but_x = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_exchange = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Search:");

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Member:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Points:");

        txt_member.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_member.setEnabled(false);

        txt_points.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_points.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_cash.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cash.setText("cash");

        lbl_momo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_momo.setText("momo");

        lbl_vnpay.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vnpay.setText("vnpay");

        lbl_discount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_discount.setText("discount");

        lbl_idEx.setForeground(new java.awt.Color(255, 255, 255));
        lbl_idEx.setText("idEx");

        lbl_totalAllDay.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalAllDay.setText("total");

        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setText("user");

        lbl_cus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cus.setText("cus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cash)
                .addGap(39, 39, 39)
                .addComponent(lbl_momo)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_user)
                        .addGap(60, 60, 60)
                        .addComponent(lbl_cus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_vnpay)
                        .addGap(49, 49, 49)
                        .addComponent(lbl_totalAllDay)))
                .addGap(56, 56, 56)
                .addComponent(lbl_discount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_idEx)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cash)
                    .addComponent(lbl_momo)
                    .addComponent(lbl_vnpay)
                    .addComponent(lbl_discount)
                    .addComponent(lbl_idEx)
                    .addComponent(lbl_totalAllDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_user)
                    .addComponent(lbl_cus)))
        );

        but_enter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_enter.setText("Enter");
        but_enter.setEnabled(false);
        but_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_enterActionPerformed(evt);
            }
        });

        but_x.setText("x");
        but_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xActionPerformed(evt);
            }
        });

        tbl_exchange.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_exchange.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Size", "Points"
            }
        ));
        tbl_exchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_exchangeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_exchange);
        if (tbl_exchange.getColumnModel().getColumnCount() > 0) {
            tbl_exchange.getColumnModel().getColumn(0).setMinWidth(70);
            tbl_exchange.getColumnModel().getColumn(0).setMaxWidth(70);
            tbl_exchange.getColumnModel().getColumn(2).setMinWidth(70);
            tbl_exchange.getColumnModel().getColumn(2).setMaxWidth(70);
            tbl_exchange.getColumnModel().getColumn(3).setMinWidth(70);
            tbl_exchange.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(623, Short.MAX_VALUE)
                        .addComponent(but_x))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(but_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_member, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_points, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(but_x)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_points, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(but_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_exchangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_exchangeMouseClicked
        // TODO add your handling code here:
        int row = tbl_exchange.getSelectedRow();                                                // Chọn sản phẩm để đổi
        double point = Double.parseDouble(String.valueOf(tbl_exchange.getValueAt(row, 3)));     // điểm của sản phẩm
        double pointCus = Double.parseDouble(txt_points.getText());                             // điểm của thằng khách
        if(pointCus<point){                                                                     // nếu như điểm thằng khách < điểm sản phẩm muốn đổi
            JOptionPane.showMessageDialog(this, "Member's point lower than product's point");   // kêu nó chọn cái nào đổi được
            but_enter.setEnabled(false);                // Không đủ điểm đổi thì khoá nút Enter lại
        }
        else{
            but_enter.setEnabled(true);                 // nếu đủ thì oke mở ra cho nó 
        }
    }//GEN-LAST:event_tbl_exchangeMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // thanh Search
        DefaultTableModel model = (DefaultTableModel)tbl_exchange.getModel();
        String search = txt_search.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);        // tạo 1 cái biến sắp xếp lại bảng theo txt search
        tbl_exchange.setRowSorter(tr);                                                                           
        tr.setRowFilter(RowFilter.regexFilter(search));                                         // sắp xếp lại theo dữ liệu search 
    }//GEN-LAST:event_txt_searchKeyReleased

    private void but_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_enterActionPerformed

        CustomerDAO cusDAO = new CustomerDAO();
        int row = tbl_exchange.getSelectedRow();                                                // lấy dòng đang chọn
        double point = Double.parseDouble(String.valueOf(tbl_exchange.getValueAt(row, 3)));     // lấy points của sản phẩm
        double pointCus = Double.parseDouble(txt_points.getText());                             // lấy points của khách
        double pointEx = pointCus - point;                              // bắt đầu trừ để lấy số dư points còn lại của khách
        
        int idEx = Integer.parseInt(String.valueOf(tbl_exchange.getValueAt(row, 0)));           // lúc này lấy cái idEx từ đầu chương trình ra sử dụng, lấy cái ID của sản phẩm muốn Exchange gán cho nó
        int idEm = Integer.parseInt(lbl_user.getText());                        // lấy id thằng nhân viên (đang bán)
        int idCus = Integer.parseInt(lbl_cus.getText());                        // lấy id thằng khách
        int totalAllDay = Integer.parseInt(lbl_totalAllDay.getText());
        int cash = Integer.parseInt(lbl_cash.getText());
        int momo = Integer.parseInt(lbl_momo.getText());
        int vnpay = Integer.parseInt(lbl_vnpay.getText());
        int discount = Integer.parseInt(lbl_discount.getText());
        int type;
        cusDAO.addPoints(pointEx, idCus);                               // sau khi đổi xong thì update điểm thằng khách theo số dư còn lại
        
        
        MemberForm m = new MemberForm(idEm, idCus, totalAllDay, cash, momo, vnpay, discount, idEx);
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_but_enterActionPerformed

    private void but_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xActionPerformed
        // nút tắt
        int idEx = 0;                                                   // nếu ko đổi gì thì đưa về 0 lại
        int idEm = Integer.parseInt(lbl_user.getText());
        int idCus = Integer.parseInt(lbl_cus.getText());
        int totalAllDay = Integer.parseInt(lbl_totalAllDay.getText());
        int cash = Integer.parseInt(lbl_cash.getText());
        int momo = Integer.parseInt(lbl_momo.getText());
        int vnpay = Integer.parseInt(lbl_vnpay.getText());
        int discount = Integer.parseInt(lbl_discount.getText());
        
        MemberForm m = new MemberForm(idEm, idCus, totalAllDay, cash, momo, vnpay, discount, idEx);
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_but_xActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExchangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExchangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExchangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExchangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExchangeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_enter;
    private javax.swing.JButton but_x;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_cash;
    private javax.swing.JLabel lbl_cus;
    private javax.swing.JLabel lbl_discount;
    private javax.swing.JLabel lbl_idEx;
    private javax.swing.JLabel lbl_momo;
    private javax.swing.JLabel lbl_totalAllDay;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_vnpay;
    private javax.swing.JTable tbl_exchange;
    private javax.swing.JTextField txt_member;
    private javax.swing.JTextField txt_points;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
