/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CustomerDAO;
import Controller.EmployeeDAO;
import Model.Customer;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MemberForm extends javax.swing.JFrame {

    /**
     * Creates new form MemberForm
     */
    public static boolean typeAction;                   // tạo biến để phân biệt action cho nút Enter

    private MemberForm() {
        
    }
    
    public void loadData(){                                                         // tải dữ liệu từ bảng Customer lên (lấy tất cả)
        DefaultTableModel model = (DefaultTableModel)tbl_member.getModel();
        CustomerDAO customerDAO = new CustomerDAO();
        ArrayList<Customer> list = customerDAO.getAll();
        int count = model.getRowCount();
        while(count>0){
            model.removeRow(count-1);
            count--;
        }
        for(Customer item:list){
            Object[] row = {item.getID(), item.getFullName(), item.getMemberType().getName()};
            model.addRow(row);
        }
    }
    
    public void getByPhone(String phone){                                               // lấy danh sách bằng Phone (dùng cho search)
        DefaultTableModel model = (DefaultTableModel)tbl_member.getModel();
        CustomerDAO customerDAO = new CustomerDAO();
        ArrayList<Customer> list = customerDAO.getByPhone(phone);
        int count = model.getRowCount();
        while(count>0){
            model.removeRow(count-1);
            count--;
        }
        for(Customer item:list){
            Object[] row = {item.getID(), item.getFullName(), item.getMemberType().getName()};
            model.addRow(row);
        }
    }
    
    public MemberForm(int idEmployee, int idCustomer, int totalAllDay, int cash, int momo, int vnPay, int discount, int idEx) {
        EmployeeDAO emDAO = new EmployeeDAO();
        CustomerDAO cusDAO = new CustomerDAO();
        initComponents();
        this.setLocationRelativeTo(null);
        if(idCustomer!=0){                                  // nếu như mà có ID thằng khách rồi thì khoá hết các nút (mắc công bấm tầm bậy tầm bạ thì dữ liệu thì rối)
            typeAction = false;
            Customer cus = cusDAO.getById(idCustomer);
            txt_id.setText(String.valueOf(idCustomer));
            txt_name.setText(String.valueOf(cus.getFullName()));
            txt_email.setText(String.valueOf(cus.getEmail()));
            txt_phone.setText(String.valueOf(cus.getPhoneNumber()));
            txt_point.setText(String.valueOf(cus.getPoints()));
            txt_type.setText(String.valueOf(cus.getMemberType().getName()));
            but_enter.setEnabled(true);                 // mở nút Enter thôi
            but_add.setEnabled(false);
            but_search.setEnabled(false);
            but_exchange.setEnabled(false);
        }
        loadData();
        lbl_idEx.setText(String.valueOf(idEx));
        lbl_cash.setText(String.valueOf(cash));
        lbl_momo.setText(String.valueOf(momo));
        lbl_vnpay.setText(String.valueOf(vnPay));
        lbl_discount.setText(String.valueOf(discount));
        lbl_totalAllDay.setText(String.valueOf(totalAllDay));
        lbl_employee.setText(String.valueOf(emDAO.getByID(idEmployee).getUsername()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_member = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_point = new javax.swing.JTextField();
        but_enter = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_type = new javax.swing.JTextField();
        lbl_totalAllDay = new javax.swing.JLabel();
        lbl_employee = new javax.swing.JLabel();
        lbl_cash = new javax.swing.JLabel();
        lbl_momo = new javax.swing.JLabel();
        lbl_vnpay = new javax.swing.JLabel();
        lbl_discount = new javax.swing.JLabel();
        but_exchange = new javax.swing.JButton();
        lbl_idEx = new javax.swing.JLabel();
        txt_searchPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        but_search = new javax.swing.JButton();
        but_add = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_member.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full name", "Type"
            }
        ));
        tbl_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_memberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_member);
        if (tbl_member.getColumnModel().getColumnCount() > 0) {
            tbl_member.getColumnModel().getColumn(0).setMinWidth(70);
            tbl_member.getColumnModel().getColumn(0).setMaxWidth(70);
            tbl_member.getColumnModel().getColumn(2).setMinWidth(120);
            tbl_member.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID:");

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Full name:");

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_name.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Phone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Points:");

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_email.setEnabled(false);

        txt_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_phone.setEnabled(false);
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });

        txt_point.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_point.setEnabled(false);

        but_enter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_enter.setText("Enter");
        but_enter.setEnabled(false);
        but_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_enterActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Type:");

        txt_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_type.setEnabled(false);

        lbl_totalAllDay.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalAllDay.setText("0");

        lbl_employee.setBackground(new java.awt.Color(255, 255, 255));
        lbl_employee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_employee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_employee.setText("Username");

        lbl_cash.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cash.setText("cash");

        lbl_momo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_momo.setText("momo");

        lbl_vnpay.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vnpay.setText("vnpay");

        lbl_discount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_discount.setText("discount");

        but_exchange.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        but_exchange.setText("Exchange");
        but_exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_exchangeActionPerformed(evt);
            }
        });

        lbl_idEx.setForeground(new java.awt.Color(255, 255, 255));
        lbl_idEx.setText("idEx");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_vnpay)
                                .addComponent(lbl_cash))
                            .addComponent(lbl_discount))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_point, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(but_exchange))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl_totalAllDay))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but_enter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_idEx)
                                        .addComponent(lbl_employee)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_momo)
                                .addGap(124, 124, 124))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbl_employee)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_totalAllDay)
                    .addComponent(lbl_momo)
                    .addComponent(lbl_idEx))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbl_cash)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_vnpay)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_discount)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_exchange))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(but_enter, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        txt_searchPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_searchPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchPhoneKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Phone:");

        but_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_search.setText("Search");
        but_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_searchActionPerformed(evt);
            }
        });

        but_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_add.setText("Add");
        but_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_searchPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_search, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_add, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(but_search, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_searchActionPerformed
        // Nút Search theo Phone
        String p = txt_searchPhone.getText();
        if(p.length() == 0) {
            loadData();
        }
        else{
            getByPhone(p);
            txt_searchPhone.setText("");
        }  
    }//GEN-LAST:event_but_searchActionPerformed

    private void tbl_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_memberMouseClicked
        // TODO add your handling code here:
        typeAction = false;                                                 // nhấp zô bảng là chuyển action là "Chọn"
        but_enter.setEnabled(true);                                             // có Action là mở nút Enter ra xài thôi :V
        DefaultTableModel model = (DefaultTableModel)tbl_member.getModel();
        CustomerDAO customerDAO = new CustomerDAO();
        int row = tbl_member.getSelectedRow();
        txt_name.setEnabled(false);
        txt_email.setEnabled(false);
        txt_phone.setEnabled(false);
        
        // lấy ID của thằng khách ra rồi in lên txt xài
        Customer customer = customerDAO.getById((int) model.getValueAt(row, 0));
        txt_id.setText(String.valueOf(model.getValueAt(row, 0)));
        txt_name.setText(String.valueOf(model.getValueAt(row, 1)));
        txt_email.setText(customer.getEmail());
        txt_phone.setText(customer.getPhoneNumber());
        txt_point.setText(String.valueOf(customer.getPoints()));
        txt_type.setText(String.valueOf(model.getValueAt(row, 2)));     
    }//GEN-LAST:event_tbl_memberMouseClicked

    private void but_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_addActionPerformed
        // Nút thêm member
        txt_name.setEnabled(true);
        txt_email.setEnabled(true);
        txt_phone.setEnabled(true);
        txt_name.setText("");
        txt_email.setText("");
        txt_phone.setText("");
        txt_id.setText("");
        txt_point.setText("0");
        txt_type.setText("Silver");
        but_enter.setEnabled(true);
        but_exchange.setEnabled(false);
        but_search.setEnabled(false);
        typeAction = true;                  // nhấn zô thì chuyển Action là "Thêm"
    }//GEN-LAST:event_but_addActionPerformed

    private void but_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_enterActionPerformed
        // Nút Enter
        CustomerDAO customerDAO = new CustomerDAO();
        if(typeAction==true){                               // xét coi Action là cái gì, nếu là "Thêm" thì dùng hàm add (trong CustomerDAO)
            Customer customer = new Customer();
            String regexEmail="[\\w]*[0-9]*[@][\\w]*[.][\\w]*";             // tạo 1 cái biến check email 
            String regexPhone="^(03|05|07|08|09)+[0-9]{8}$";                // tạo 1 cái biến check phone
            boolean check=false;                                            // biến check email coi true hay fasle 
            boolean check1=false;                                           // biến check phone coi true hay fasle
            String name = txt_name.getText();
            String phone = txt_phone.getText();
            String email = txt_email.getText();
            Pattern pattern = Pattern.compile(regexEmail);
            Pattern pattern1 = Pattern.compile(regexPhone);
            Matcher matcher = pattern.matcher(email);
            Matcher matcher1 = pattern1.matcher(phone);
            check=matcher.find();
            check1=matcher1.find();
            if(name.length()==0 || phone.length()==0 || email.length()==0){
                JOptionPane.showMessageDialog(this, "Please input full information");
            }
            else if(check==false){                                          // nếu mà điền ko đúng loại email thì bắt nhập lại 
                JOptionPane.showMessageDialog(this, "Please input another email (Email by format asd123@def.com)");
            }
            else if(check1==false){                                         //  nếu mà sđt tào lao thì bắt nhập lại 
                JOptionPane.showMessageDialog(this, "Invalid phone number");
            }
            else{
                customer.setMemberTypeID(1);                                // thành viên mới thì đưa nó về Silver
                customer.setFullName(name);
                customer.setEmail(email);
                customer.setPhoneNumber(phone);
                customer.setPoints(0);                                      // đưa Points về 0 (vì nó mới là member vs nó đã mua j đâu ~)
                customer.setStatus(true);
                
                if(customerDAO.add(customer))               // nếu thêm thành công thì đưa form về lại ban đầu
                { 
                    loadData(); 
                    txt_name.setEnabled(false);
                    txt_email.setEnabled(false);
                    txt_phone.setEnabled(false);
                    but_enter.setEnabled(false);
                    but_search.setEnabled(true);
                    txt_name.setText("");
                    txt_email.setText("");
                    txt_phone.setText("");
                    txt_type.setText("");
                    txt_point.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Add fail");            // nếu mà add ko dc thì...
                }
            }
        }
        else{                                               // nếu là "Chọn" thì lấy ID của member đó rồi xử lý tích điểm cho nó 
            EmployeeDAO emDAO = new EmployeeDAO();
            int totalAllDay = Integer.parseInt(lbl_totalAllDay.getText());
            int id = Integer.parseInt(txt_id.getText());
            customerDAO.getById(id);
            int idCustomer = Integer.parseInt(txt_id.getText());
            int cash, momo, vnPay, discount, idEx;
            cash = Integer.parseInt(lbl_cash.getText());
            momo = Integer.parseInt(lbl_momo.getText());
            vnPay = Integer.parseInt(lbl_vnpay.getText());
            discount = Integer.parseInt(lbl_discount.getText());
            idEx = Integer.parseInt(lbl_idEx.getText());
            SaleForm s = new SaleForm(Integer.parseInt(String.valueOf(emDAO.getByUsername(lbl_employee.getText()).getID())), id, totalAllDay, cash, momo, vnPay, discount, idEx);
            s.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_but_enterActionPerformed

    private void but_exchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_exchangeActionPerformed
        // Nút Exchange
        String strID = txt_id.getText();
        if(strID.equals("36") || strID.length()==0){                            // Nếu là chọn dòng có ID = 36 (là value rác trong database)
            JOptionPane.showMessageDialog(this, "Please choose 1 member");      // thì kêu nó chọn member khác
        }
        else{                                           // Còn nếu chọn member bình thường thì hiện bảng Exchange lên rồi xử lý thôi :V
            EmployeeDAO emDAO = new EmployeeDAO();
            int idCustomer = Integer.parseInt(txt_id.getText());
            int idEmployee = Integer.parseInt(String.valueOf(emDAO.getByUsername(lbl_employee.getText()).getID()));
            int cash, momo, vnpay, discount, total, idEx;
            cash = Integer.parseInt(lbl_cash.getText());
            momo = Integer.parseInt(lbl_momo.getText());
            vnpay = Integer.parseInt(lbl_vnpay.getText());
            discount = Integer.parseInt(lbl_discount.getText());
            total = Integer.parseInt(lbl_totalAllDay.getText());
            idEx = Integer.parseInt(lbl_idEx.getText());
        
            ExchangeForm e = new ExchangeForm(idEmployee, idCustomer, total, cash, momo, vnpay, discount, idEx);
            e.setLocationRelativeTo(null);
            e.setVisible(true);
            this.dispose();
        }   
    }//GEN-LAST:event_but_exchangeActionPerformed

    private void txt_searchPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchPhoneKeyTyped
        // ràng buộc text, chỉ được nhập số
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_searchPhoneKeyTyped

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        // ràng buộc text, chỉ được nhập số
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_phoneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_add;
    private javax.swing.JButton but_enter;
    private javax.swing.JButton but_exchange;
    private javax.swing.JButton but_search;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_cash;
    private javax.swing.JLabel lbl_discount;
    private javax.swing.JLabel lbl_employee;
    private javax.swing.JLabel lbl_idEx;
    private javax.swing.JLabel lbl_momo;
    private javax.swing.JLabel lbl_totalAllDay;
    private javax.swing.JLabel lbl_vnpay;
    private javax.swing.JTable tbl_member;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_point;
    private javax.swing.JTextField txt_searchPhone;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables
}
